branches:
  except:
  - /.*(.tmp)$/

language: rust

matrix:
  include:
  - os: osx
    rust: 1.22.0
  - os: osx
    rust: nightly
  - rust: nightly
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check
    - cargo test --features "serde std v1 v3 v4 v5"
    - cargo bench --features "serde std v1 v3 v4 v5"
  - os: linux
    rust: nightly
    script:
    - cargo test --features "const_fn"

notifications:
  email:
    on_success: never

os: linux

rust:
- 1.22.0
- stable
- beta
- nightly

script:
- cargo test --no-default-features
- cargo test
- cargo test --features "serde"
- cargo test --features "v1"
- cargo test --features "v3"
- cargo test --features "v4"
- cargo test --features "v5"
- cargo test --features "slog"
- cargo test --features "serde std v1 v3 v4 v5"

sudo: false
